---
engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript: true
  remark-lint:
    enabled: true
  fixme:
    enabled: true

ratings:
  paths:
    - "src/*.js"

exclude_paths:
- "docs/"
- "dist/"
- "test/"
