language: node_js
node_js:
  - "7"
addons:
  code_climate:
    repo_token: 49eddeba6c3d0713fb7959b0460acee77bf8796cc4d9b75fec5b0c55cb0b4411
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info
